import Head from "next/head";
import { PostForm } from "~/components/Post/Form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Y</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostForm />
      </main>
    </>
  );
}
