/* eslint-disable @typescript-eslint/no-unsafe-return */
import Head from "next/head";
import { PostForm, PostsList } from "~/components/Post";
import { LoadingSkeleton } from "~/components/base/LoadingSkeleton";
import { POSTS_LIMIT } from "~/constants";
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.post.getLatest.useInfiniteQuery(
    {
      limit: POSTS_LIMIT,
    },
    {
      getNextPageParam: (lastPage) => lastPage.nextCursor,
    },
  );

  return (
    <>
      <Head>
        <title>Y</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostForm />
      {isLoading && <LoadingSkeleton />}
      {!isLoading &&
        data?.pages.map((page, index) => (
          <PostsList key={index} posts={page.posts} />
        ))}
    </>
  );
}
