import Head from "next/head";
import { useParams } from "next/navigation";
import { PostCard } from "~/components/Post/Card";
import { ResponseList } from "~/components/Post/Response/List";
import { Button } from "~/components/base";
import { LoadingSkeleton } from "~/components/base/LoadingSkeleton";
import { usePostForm } from "~/context/PostForm.Context";
import { api } from "~/utils/api";

export default function PostPage() {
  const params = useParams<{ id: string }>();
  const { setProps } = usePostForm();

  const { data: post, isLoading: isLoadingPost } = api.post.getById.useQuery({
    id: Number(params?.id),
  });

  function handleReply() {
    if (!post) return;
    setProps({
      openModal: true,
      responseTo: {
        id: post.id,
        title: post.title,
      },
    });
  }

  if (isLoadingPost) return <LoadingSkeleton />;
  if (!post)
    return (
      <div className="flex justify-center">
        <h1>Post não encontrado</h1>
      </div>
    );
  return (
    <>
      <Head>
        <title>Y - {post.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostCard post={post} />
      <div className="flex w-full justify-center text-center">
        <Button className="w-full" onClick={() => handleReply()}>
          Responder
        </Button>
      </div>
      <ResponseList postId={post.id} />
    </>
  );
}
